vm:
  hosts:
    os-builder:
      ansible_port: 22
      ansible_host: "{{ vm_ip }}"
      ansible_user: ubuntu
master:
  hosts:
    master1:
      rpi_static_ip: 10.0.90.10
      ansible_port: 5555
      load_balancer_addresses:
        - 10.0.90.20-10.0.90.99
node:
  hosts:
    node1:
      rpi_static_ip: 10.0.90.11
      ansible_port: 5551
    node2:
      rpi_static_ip: 10.0.90.12
      ansible_port: 5552
cluster:
  children:
    master:
    node:
