---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: registry-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ registry_volume_prefix }}-pv
spec:
  capacity:
    storage: {{ registry_storage_capacity }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: registry-storage
  local:
    path: {{ registry_folder }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role
          operator: In
          values:
          - database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ registry_volume_prefix }}-pvc
  labels:
    app: registry
spec:
  storageClassName: registry-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ registry_storage_capacity }}
