---
vhosts:
  hosts:
    vhost:
      ansible_host: 127.0.0.1
      ansible_user: vagrant
      ansible_port: 2222
      force_handlers: True
      image_mount_point: /mnt/os
      jailed_user: jailed

jailed_rpis:
  hosts:
    rpi1:
      ansible_host: 127.0.0.1
      ansible_user: jailed
      ansible_port: 2222
