---
k8s_master:
    hosts:
      rpi1:
        ansible_host: 192.168.8.134
        ansible_user: ubuntu
      rpi2:
        ansible_host: 192.168.8.156
        ansible_user: ubuntu
      rpi3:
        ansible_host: 192.168.8.174
        ansible_user: ubuntu
