---
- hosts: vhosts
  gather_facts: no
  roles:
    - role: prepare_os
      become: true
    - role: chroot_jail
      become: true

- hosts: jailed_rpis
  gather_facts: no
  tasks:
  - name: Just a debug statement
    shell: "echo 'Works!'"
