---
- name: Install base dependencies
  apt:
    name:
      - snapd
    state: present
  become: yes

- name: Disable Swap
  command: swapoff -a

- name: Enable cgroups
  lineinfile:
    dest: /boot/firmware/cmdline.txt
    regexp: '^net.ifnames'
    line: "net.ifnames=0 dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc cgroup_enable=memory cgroup_memory=1"
    state: present
  register: cgroups_enabled

- name: Reboot host and wait for it to restart
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: cgroups_enabled.changed

- name: Install MicroK8s
  become: yes
  snap:
    name: microk8s
    classic: yes
    channel: "{{ microk8s_version }}"
  register: install_microK8s

- name: Restart MicroK8s and check status
  import_tasks: restart-microK8s.yml
  when: install_microK8s.changed

- name: Alias kubectl
  shell: "source /etc/profile.d/apps-bin-path.sh && snap alias microk8s.kubectl kubectl"
  args:
    executable: /bin/bash
