- name: Microk8s status
  shell: source /etc/profile.d/apps-bin-path.sh && microk8s.status --wait-ready
  args:
    executable: /bin/bash

- name: Stop Microk8s
  shell: source /etc/profile.d/apps-bin-path.sh && microk8s.stop
  args:
    executable: /bin/bash

- name: Start Microk8s
  shell: source /etc/profile.d/apps-bin-path.sh && microk8s.start
  args:
    executable: /bin/bash
  retries: 3
  delay: 3
  register: result
  until: result.rc == 0

- name: Microk8s status
  shell: source /etc/profile.d/apps-bin-path.sh && microk8s.status --wait-ready
  args:
    executable: /bin/bash

- name: Microk8s inspect
  shell: source /etc/profile.d/apps-bin-path.sh && microk8s.inspect
  args:
    executable: /bin/bash
