---

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Clear localhosts
  lineinfile:
    path: "/etc/hosts"
    state: absent
    regexp: '^127\.0\.0\.1 *'

- name: Add hostname and localhost to hosts
  lineinfile:
    path: "/etc/hosts"
    line: "{{ item }}"
  with_items:
    - "127.0.0.1 localhost"
    - "127.0.0.1 {{ inventory_hostname }}"

- name: Ensure the cloud config directory exists
  ansible.builtin.file:
    path: /etc/cloud/cloud.cfg.d/
    state: directory
    mode: '0755'

- name: Clear cloud network init config
  copy:
    dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
    content: "network: {config: disabled}"

- name: "Ensure cloud network generated config file is absent"
  ansible.builtin.file:
    path: /etc/netplan/50-cloud-init.yaml
    state: absent

- name: Set appliance static IP
  template:
    src: files/00-appliance-init.yaml.j2
    dest: /etc/netplan/00-appliance-init.yaml
    force: yes
    mode: 640

- name: "Ensure K3s master service is enabled and started (fire and forget)"
  systemd:
    name: k3s
    daemon_reload: yes
    enabled: yes
    state: "started"
    no_block: yes
  when: is_master

- name: "Ensure K3s node service is enabled"
  systemd:
    name: k3s-node
    daemon_reload: yes
    enabled: yes
  when: not is_master

- name: "Wait for K3s master to start"
  shell: k3s kubectl get nodes
  register: result
  until: result.rc == 0
  retries: 30
  delay: 5
  when: is_master
