---
- name: Create a user for the chroot jail
  user:
    name: "{{ jailed_user }}"
    comment: Jailed User with chroot access

- name: Configure the sshd_config to redirect to chroot
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "{{ item }}"
  with_items:
    - "Match User {{ jailed_user }}"
    - "ChrootDirectory {{ image_mount_point }}"

- name: "Create 'home/{{jailed_user}}/.ssh' folder"
  file:
    path: "home/{{jailed_user}}/.ssh"
    state: directory

# TODO: Add the correct Public Key to /home/jailed/.ssh/authorized_keys
# TODO: Set the access rights appropriately
