---
is_master: true
ansible_host: "{{ vm_ip }}"
ansible_user: "{{ cluster_user }}"
rpi_static_ip: "{{ master_static_ip }}"
cluster_disk: present
cluster_disk_mount_point: /mnt/disks/ssd1
cluster_disk_label: cluster-disk
ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
