# Preloaded list of valid tokens to join
k8s_token_list:
  - q4T9AoMCycmTUSquijZpsdcxCM0oGvPE
  - zOMJIpOq5GUphmsyA3Vol6fdJiPLvEfy
  - 3WCqcF1iGg56ljbyEQaCVjOPZKNpJ4n9
  - 9I3iayq9YbDSb8RJrpZ2lo5a6Al5Gc3K
  - aXqUBBLSHO6EM2FdKE6lYrk7nFGEI3L8
  - v1MTggIEzfLZGML862q1HyVFGdtj8Z61
  - YJzHhVuDRwHKEyvTtvsjzYr6s2FLDJTt
  - iE373E69dVng0ulqbHulI1R5XRx60Lko
  # - zE9SJuOv206jcxZpcOmaB9Gy5KU7D2fK
  # - VhdnbyeLHFdD3xHwPOL9ZyYEXNcjdEt1
  # - vXFIpaTRmYq3Ie2cB3kWgbTmF1glGHsW
  # - gkL5QjQoePJk4rS97ec6sE1XxfaHIhJF
  # - ITxDYEIAdoHHZWv9bQqWYdMrjHg3CIhB
  # - zplOOujkgBaTwPzU4DcgmSwm6IdqFz5j
  # - PTjp9JWigAC6mk4EeCfIghF8EH5l94Ow
  # - 8rulyNOoUmz008lRYZjLXmn0mFgYTvA8
  # - ezvtB57TCYU9h3shgBBEW1MEjCrl2DIt
  # - dMyOIojHMaDDzsTq2EhiHNdyNKDX89Dh
  # - D4PmS74KRpp1StyTVqdW3xGqTwiWhaGG
  # - nCTNButs0EHmTp3xQerChttWaZ7hXA0H
  # - ZmFNNhz3kkNotAp4JXsEG41xkYn7PBNf
  # - Z8DR3PthruoBfNE2MRxUVFx4RMpaWOVi
  # - DuDQZD5UQy5F9m29FgHxPFEB5Sh6UN75
  # - AASuol1NI7bBWf67hrUjEW6PqEsINUIB
  # - oRT2JoBsLRhMDjlxWTEk44gnZLtpWFwJ
  # - 2UJ6JvSziE1uBEt2FDd4jCv1UuE966lM
  # - qwGoJZgzBiUPWeOLn7iSgkvcYECGrwPi
  # - m0AMriwI2Lkl7rIxuqEwKtHJY1pMVpji
  # - N5oZYvCVLKghWvVKfqNlO38jhH8OG3ZJ
  # - myW2xh658qklh7mcM62KTR5Dt5Yrw6hv
  # - w0DOxYZ4BiGKKRFNloPFLA6psEda6BTj
  # - E6o68REB3i4Tbiz2N9XurjvnXLsXlKrj
  # - xfK5Z1nbWLikMNLCcdSYdVJyjFLShOXJ
  # - OZb2nZTZk27atZzZ0t57QM4v2SpZaDuS
  # - 45bjHuCISLVOVxZZVoNqbY0n7WW9rc1n
  # - kuImQucoDVhgZtSfMRFUTCSBLczjEKzB
  # - QFCNLBz38gjFgPyrCMveslEGcDcQ3Fl0
  # - F7eYXfJ8OFPhO8XR8B8ApuU6Ef6fyzPB
  # - dloJHBaIDUjxjBR1cG9YJjCE3WhS1Pl1
  # - JubfpAxFbT5kHp5TdhcvnZcuH5Jl1IFT
  # - qXZYR3AH6o5sJ03FHOR3SFM9NXwfIYLH
  # - ede3llrtSNkv6H2AjIu9mZeZyrfx7OZh
  # - bdBPw9VNxy0tdGzixdtdV1jCrtR4aPQP
  # - acXEMSuPS5jjMTO9u97XLuplAxpBkNEz
  # - TKU1XOzfWZ4DQ5VkCA5gSPLP5aEB3WHa
  # - X1XjgOsJ5oKoyzECSO7UhEiQCBcSaxUD
  # - zICykxVv0qsZQkgs6aGZq8haPABA46qq
  # - SFWFTRwxXzMaiptae3LTeeWUqBRuDfrn
  # - 5nAnFxlmm8o8Lgtsu65uj8WZPWjWvuX5
  # - kIK7RJURFhMYf9nCcSDv71hUB9w17dIV
